### ISSUE TITLE
Pyaudio has failed to load in python

### ISSUE THREAD

**Issue by Melloking1123** [NONAN23x/WhisperingNova#4]
As i mentioned in the title i m facing issues to load pyaudio in python

**Comment by NONAN23x** [comment]
Thanks for reporting the issue,
The issue is caused by your distro manager's Python version lacking some dependencies of some sort,
Most likely you are on Debian-Based Operating System, so you need to install some packages for your OS: use the command line:
`sudo apt-get install libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0 ffmpeg`
Then simply:
`pip install -r requirements.txt`

**Comment by Melloking1123** [comment]
Thanks for responding the issue is solved
